### ISSUE TITLE
Test for Challenge II

### ISSUE THREAD

**Issue by AyanCoders** [learn-co-curriculum/my-first-hash#12] opened 2018-01-15 23:36 UTC
Test for Challenge II expects method to return hash but it is not specified in the instructions that the method needs to return a hash.

ie. If you follow the instructions, you will get an error.

**Comment by curiositypaths** [comment] 2018-01-23 21:23
Thanks for reporting this issue. We're now aware of it and are tracking it in issue #15. We will add this to our internal work queue. 

We're closing this issue but invite you to follow the progress. We will notify you when the issue is resolved.

-- Flatiron Curriculum Team

**Closed as completed by curiositypaths** 2018-01-23 21:23 UTC
Labels: Curriculum
