### ISSUE TITLE
Challenge IV #adding test expectation does not match 

### ISSUE THREAD

**Issue by jaf7** [learn-co-curriculum/my-first-hash#14] opened 2018-01-18 16:28 UTC
The **Challenge IV: Adding Data** instructions don't match the corresponding test. The instructions specify to add:

`shipping_manifest.[]=( "muskets", 2 )`
`shipping_manifest.[]=( "gun powder", 4 )`

But the test for the #adding method expects:

`shipping_manifest.[]=( "pearl necklace", 1 )`

**Comment by curiositypaths** [comment] 2018-01-23 21:24
Thanks for reporting this issue. We're now aware of it and are tracking it in issue #15. We will add this to our internal work queue. 

We're closing this issue but invite you to follow the progress. We will notify you when the issue is resolved.

-- Flatiron Curriculum Team

**Closed as completed by curiositypaths** 2018-01-23 21:24 UTC
Labels: test
