### ISSUE TITLE
CHALLENGE IV Error

### ISSUE THREAD

**Issue by MatthewDtotheG** [learn-co-curriculum/my-first-hash#13] opened 2018-01-18 02:48 UTC
The read me for challenge IV asks for muskets and gun powder to be added to the shipping manifest hash but the test in the IDE will only pass if one pearl necklace is added.

**Comment by curiositypaths** [comment] 2018-01-23 21:24
Thanks for reporting this issue. We're now aware of it and are tracking it in issue #15. We will add this to our internal work queue. 

We're closing this issue but invite you to follow the progress. We will notify you when the issue is resolved.

-- Flatiron Curriculum Team

**Closed by curiositypaths** 2018-01-23 21:24 UTC
Labels: Curriculum
