### ISSUE TITLE
Challenge 4 has Incorrect Instructions

### ISSUE THREAD

**Issue by GuttermanA** [learn-co-curriculum/my-first-hash#10] opened 2017-12-12 20:47 UTC
Says has should look like:

"whale bone corsets" => 5
"porcelain vases" => 2
"oil paintings" => 3
"muskets" => 2
"gun powder" => 4

while the test in the lab says it should look like:

"whale bone corsets" => 5
"porcelain vases" => 2
"oil paintings" => 3
"pearl necklace" => 1

**Comment by curiositypaths** [comment] 2018-01-23 21:23
Thanks for reporting this issue. We're now aware of it and are tracking it in issue #15. We will add this to our internal work queue. 

We're closing this issue but invite you to follow the progress. We will notify you when the issue is resolved.

-- Flatiron Curriculum Team

**Closed as completed by curiositypaths** 2018-01-23 21:23 UTC
Labels: test
