### ISSUE TITLE
rspec for challenge 4

### ISSUE THREAD

**Issue by f3igao** [learn-co-curriculum/my-first-hash#11] opened 2017-12-15 23:16 UTC
the collections_practice_spec.rb file seems outdated for challenge 4. the rspec tests against adding a "pearl necklace" item, while the instruction on learn.co says to add "muskets" and "gun powder."

**Comment by curiositypaths** [comment] 2018-01-23 21:23
Thanks for reporting this issue. We're now aware of it and are tracking it in issue #15. We will add this to our internal work queue. 

We're closing this issue but invite you to follow the progress. We will notify you when the issue is resolved.

-- Flatiron Curriculum Team

**Closed as completed by curiositypaths** 2018-01-23 21:23 UTC
Labels: Curriculum
